services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mrmandu
    ports:
      - "5432:5432"
    volumes:
      - mrmandu-db:/var/lib/postgresql/data
volumes:
  mrmandu-db:
